//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAEAPIServer) DeepCopyInto(out *SAEAPIServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAEAPIServer.
func (in *SAEAPIServer) DeepCopy() *SAEAPIServer {
	if in == nil {
		return nil
	}
	out := new(SAEAPIServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAEAPIServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAEAPIServerCredential) DeepCopyInto(out *SAEAPIServerCredential) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAEAPIServerCredential.
func (in *SAEAPIServerCredential) DeepCopy() *SAEAPIServerCredential {
	if in == nil {
		return nil
	}
	out := new(SAEAPIServerCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAEAPIServerList) DeepCopyInto(out *SAEAPIServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SAEAPIServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAEAPIServerList.
func (in *SAEAPIServerList) DeepCopy() *SAEAPIServerList {
	if in == nil {
		return nil
	}
	out := new(SAEAPIServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAEAPIServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAEAPIServerProxy) DeepCopyInto(out *SAEAPIServerProxy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAEAPIServerProxy.
func (in *SAEAPIServerProxy) DeepCopy() *SAEAPIServerProxy {
	if in == nil {
		return nil
	}
	out := new(SAEAPIServerProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAEAPIServerProxyOptions) DeepCopyInto(out *SAEAPIServerProxyOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAEAPIServerProxyOptions.
func (in *SAEAPIServerProxyOptions) DeepCopy() *SAEAPIServerProxyOptions {
	if in == nil {
		return nil
	}
	out := new(SAEAPIServerProxyOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SAEAPIServerProxyOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAEAPIServerSpec) DeepCopyInto(out *SAEAPIServerSpec) {
	*out = *in
	out.SAEAPIServerCredential = in.SAEAPIServerCredential
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAEAPIServerSpec.
func (in *SAEAPIServerSpec) DeepCopy() *SAEAPIServerSpec {
	if in == nil {
		return nil
	}
	out := new(SAEAPIServerSpec)
	in.DeepCopyInto(out)
	return out
}
